name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache
      VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'
    
    steps:
        - name: Set up cache
          uses: actions/github-script@v7
          with:
            script: |
              core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
              core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

        - uses: actions/checkout@v4
        - name: "Create directory '${{ env.VCPKG_DEFAULT_BINARY_CACHE }}'"
          run: mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
          shell: bash

        - uses: lukka/get-cmake@latest

        - name: Set up vcpkg
          uses: lukka/run-vcpkg@v4
          with:
            setupOnly: true
            vcpkgGitCommitId: 0affe8710a4a5b26328e909fe1ad7146df39d108