name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache
      VCPKG_BINARY_SOURCES: 'clear;x-gha,readwrite'
    
    steps:
        - name: Set up cache
          uses: actions/github-script@v7
          with:
            script: |
              core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
              core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

        - uses: actions/checkout@v4
        - name: "Create directory '${{ env.VCPKG_DEFAULT_BINARY_CACHE }}'"
          run: mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
          shell: bash

        - uses: lukka/get-cmake@latest

        - name: Set up vcpkg
          uses: lukka/run-vcpkg@v4
          with:
            setupOnly: true
            vcpkgGitCommitId: 0affe8710a4a5b26328e909fe1ad7146df39d108
        
        # Restore vpkg cache
        - name: Restore vcpkg
          uses: actions/cache@v4
          with:
            path: |
              ${{ env._VCPKG_ }}
              !${{ env._VCPKG_ }}/buildtrees
              !${{ env._VCPKG_ }}/packages
              !${{ env._VCPKG_ }}/downloads
              !${{ env._VCPKG_ }}/installed
            key: |
              ${{ hashFiles( '.git/modules/vcpkg/HEAD' )}}
          
        # Ensure that the developer command promt is present on Windows runners
        - uses: ilammy/msvc-dev-cmd@v1

        - name: Install packages
          run: apt-get install -y libxi-dev && apt-get install -y libxtst-dev
        - name: Restore from cache the dependencies and generate project files
          run: |
            cmake -DBUILD_EXAMPLE_APP=ON -DBUILD_TESTS=ON --preset linux-release

        - name: Build (Release configuration)
          run: |
            cmake --build --preset linux-release

        - name: Test
          run: |
            ctest --preset videolib-linux